### PR TITLE
Add capacity getter to fix example demo.

### PR DESCRIPTION
**Pull request by beregond**

### CODE REVIEW

**Comment by bjoernQ** [comment]
Both examples should just compile as they are using the implementation here: https://github.com/esp-rs/esp-storage/blob/869f6c8c258bfe579b64f856bbbb38c9b8a381d1/src/storage.rs#L37-L41

It's part of the embedded-storage ReadStorage trait ( https://docs.rs/embedded-storage/0.3.1/embedded_storage/trait.ReadStorage.html#tymethod.capacity )

What errors do you get?

**Comment by beregond** [comment]
with this in cargo.toml:
```
esp-storage = { version = "0.3.0", features = ["esp32c3"]}
```
and code copied to main from demo
```
    let mut flash = FlashStorage::new();
    println!("Flash size = {}", flash.capacity);
```
I get this on build:
```
error[E0616]: field `capacity` of struct `FlashStorage` is private
  --> src/main.rs:53:39
   |
53 |     println!("Flash size = {}", flash.capacity);
   |                                       ^^^^^^^^ private field
```

...of course in demo it is actually `flash.capacity()`, so then it is:
```
error[E0599]: no method named `capacity` found for struct `FlashStorage` in the current scope
  --> src/main.rs:53:39
   |
53 |     println!("Flash size = {}", flash.capacity());
   |                                       ^^^^^^^^ private field, not a method
```

**Comment by bjoernQ** [comment]
Ah - you will need to depend on https://crates.io/crates/embedded-storage and have the traits in scope `use embedded_storage::{ReadStorage, Storage};`

**Comment by beregond** [comment]
Right, that worked, thanks!

**Comment by bjoernQ** [comment]
Thanks for the feedback. I might want to merge this anyways since it would be nice if users could use our crates without adding a dependency just to import traits. Do you remember if there was anything else?

You can re-open this PR and I'll merge it. Thanks

**Pull request closed without merging**
